name: 提取 boot / init_boot.img

on:
  push:
  workflow_dispatch:

jobs:
  YIJIANTIQU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
            

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install tree
          sudo apt-get -y install python3-pip aria2 liblzma-dev brotli lz4
          pip3 install backports.lzma pycrypto
          pip install protobuf==3.20

      - name: 提取镜像
        run: |
          cd ~
          git clone --recurse-submodules https://github.com/tosasitill/Firmware_extractor.git
          cd Firmware_extractor
          aria2c -s 10 -x 10 -d . -o firmware.zip http://liaoke.link:5244/d/123%E7%BD%91%E7%9B%98/LITE%E6%89%8B%E5%B7%A5%E5%AE%98%E6%94%B9_%E5%B0%8F%E7%B1%B312S_OS1.0.24.6.10.DEV_14_9c95f6efb158e242be47165fb61b6e7d.zip
          ./extractor.sh firmware.zip
          if [ -f "init_boot.img" ]; then
            mkdir -p out
            mv init_boot.img out/
            echo "init_boot.img has been moved to the out folder."
          else
            echo "init_boot.img not found."
          fi
          tree
      - name: Upload .img file as artifact
        uses: actions/upload-artifact@main
        with:
          name: boot.img  # 这里设置 artifact 的名称
          path: ~/Firmware_extractor/out/boot.img  # 这里设置要上传的文件的路径
          
      - name: Upload firmware.zip as artifact
        uses: actions/upload-artifact@main
        with:
          name: firmware.zip  # 这里设置 artifact 的名称
          path: ~/Firmware_extractor/firmware.zip  # 这里设置要上传的文件的路径
          
      - name: Check and upload init_boot.img as artifact
        run: |
          # 切换到 out 目录
          cd ~/Firmware_extractor/out
          # 检查 init_boot.img 文件是否存在
          if [ -f "init_boot.img" ]; then
            # 文件存在，上传 artifact
            echo "init_boot.img found. Uploading..."
            # 设置输出变量，以便在下一个步骤中使用
            echo "img_file=init_boot.img" >> $GITHUB_ENV
          else
            # 文件不存在，打印消息
            echo "init_boot.img not found. Skipping upload."
          fi

      - name: Upload init_boot.img as artifact
        if: env.img_file == 'init_boot.img'  # 只有在上一步中找到文件时才执行这个步骤
        uses: actions/upload-artifact@main
        with:
          name: init_boot.img
          path: ~/Firmware_extractor/out/init_boot.img
