name: 提取 boot / init_boot.img

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: 'https://cdnorg.d.miui.com/OS1.0.3.0.ULTCNXM/miui_MAYFLY_OS1.0.3.0.ULTCNXM_2d7643fb8d_14.0.zip'

jobs:
  YIJIANTIQU:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install tree
          sudo apt-get -y install python3-pip aria2 liblzma-dev brotli lz4
          pip3 install backports.lzma pycrypto
          pip install protobuf==3.20

      - name: 提取镜像
        run: |
          cd ~
          git clone --recurse-submodules https://github.com/tosasitill/Firmware_extractor.git
          cd Firmware_extractor
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          ./extractor.sh firmware.zip
          if [ -f "init_boot.img" ]; then
            mkdir -p out
            mv init_boot.img out/
            echo "init_boot.img has been moved to the out folder."
          else
            echo "init_boot.img not found."
          fi
          tree
      - name: 检测并上传 .img 文件作为 artifacts
        run: |
          # 切换到 out 目录
          cd ~/Firmware_extractor/out
          # 查找所有的 .img 文件
          for img_file in *.img; do
            # 检查文件是否存在
            if [ -f "$img_file" ]; then
              # 上传文件到 artifacts
              echo "Uploading $img_file to artifacts..."
              # 设置输出变量，以便在下一个步骤中使用
              echo "img_file=$img_file" >>$GITHUB_ENV
            else
              echo "File not found: $img_file"
            fi
          done
      - name: Upload .img file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: boot.img  # 这里设置 artifact 的名称
          path: ~/Firmware_extractor/out/boot.img  # 这里设置要上传的文件的路径
