name: 提取 boot / init_boot.img

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: 'https://cdnorg.d.miui.com/OS1.0.3.0.ULTCNXM/miui_MAYFLY_OS1.0.3.0.ULTCNXM_2d7643fb8d_14.0.zip'

jobs:
  YIJIANTIQU:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install tree
          sudo apt-get -y install python3-pip aria2 liblzma-dev brotli lz4
          pip3 install backports.lzma pycrypto
          pip install protobuf==3.20

      - name: 提取镜像
        run: |
          cd ~
          git clone --recurse-submodules https://github.com/tosasitill/Firmware_extractor.git
          cd Firmware_extractor
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          ./extractor.sh firmware.zip
          if [ -f "init_boot.img" ]; then
            mkdir -p out
            mv init_boot.img out/
            echo "init_boot.img has been moved to the out folder."
          else
            echo "init_boot.img not found."
          fi
          tree
          cd ~/Firmware_extractor/out
      - name: List .img files
         run:|
          find /home/runner/Firmware_extractor/out -type f -name "*.img" -execdir echo {} \;
      - name: Upload .img files as artifacts
        run: |
         find /home/runner/Firmware_extractor/out -type f -name "*.img" | while read img_file; do
          echo "Uploading $img_file to artifacts..."
          artifact_name=$(basename "$img_file")
          echo "artifact_name=$artifact_name" >>$GITHUB_ENV
          echo "artifact_path=$img_file" >>$GITHUB_ENV
          echo "::set-output name=artifact_name::$artifact_name"
          echo "::set-output name=artifact_path::$img_file"
        done
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifact_name }}
        path: ${{ env.artifact_path }}
